insert into iut (nomIut, adresse, nbEtudiants) values ("Mans", "AVENUE OLIVIER MESSIAEN 72085 LE MANS CEDEX 9", "35012");
insert into iut (nomIut, adresse, nbEtudiants) values ("Schiltigheim", "1 ALLEE D'ATHENES 67300 SCHILTIGHEIM", "29974");
insert into iut (nomIut, adresse, nbEtudiants) values ("Corte", "QUARTIER GRIMALDI 20250 CORTE", "25504");
insert into iut (nomIut, adresse, nbEtudiants) values ("Angers", "4 BOULEVARD LAVOISIER 49016 ANGERS CEDEX 01", "29650");
insert into iut (nomIut, adresse, nbEtudiants) values ("Rodez", "33 AVENUE DU 8 MAI 1945 12006 RODEZ CEDEX", "13106");
insert into iut (nomIut, adresse, nbEtudiants) values ("Quimper", "2 RUE DE L'UNIVERSITE 29334 QUIMPER CEDEX", "32699");
insert into iut (nomIut, adresse, nbEtudiants) values ("Tarbes", "1 RUE LAUTREAMONT 65016 TARBES CEDEX", "18492");
insert into iut (nomIut, adresse, nbEtudiants) values ("Cergy-Pontoise", "RUE D'ERAGNY 95031 CERGY PONTOISE CEDEX", "28243");
insert into iut (nomIut, adresse, nbEtudiants) values ("Vannes", "8 RUE MONTAIGNE 56017 VANNES CEDEX", "17967");
insert into iut (nomIut, adresse, nbEtudiants) values ("Paris-VII", "2 PLACE JUSSIEU 75251 PARIS CEDEX 05", "10400");
insert into iut (nomIut, adresse, nbEtudiants) values ("Perpignan", "CHEMIN DE LA PASSIO VELLA 66962 PERPIGNAN CEDEX", "11486");
insert into iut (nomIut, adresse, nbEtudiants) values ("Kourou", "LOTISS. BRANLY 4 AV CHAUDAT 97387 KOUROU CEDEX", "14686");
insert into iut (nomIut, adresse, nbEtudiants) values ("Lannion", "RUE EDOUARD BRANLY 22302 LANNION CEDEX", "16062");
insert into iut (nomIut, adresse, nbEtudiants) values ("Rennes", "3 RUE DU CLOS COURTEL 35014 RENNES CEDEX 7", "26125");
insert into iut (nomIut, adresse, nbEtudiants) values ("Toulouse", "115 ROUTE DE NARBONNE 31077 TOULOUSE CEDEX", "32992");
insert into iut (nomIut, adresse, nbEtudiants) values ("La Réunion", "40 AVENUE DE SOWETO 97455 ST PIERRE CEDEX", "23617");
insert into iut (nomIut, adresse, nbEtudiants) values ("Amiens", "AVENUE DES FACULTES 80025 AMIENS CEDEX 1", "37828");
insert into iut (nomIut, adresse, nbEtudiants) values ("Evry", "22 ALLEE JEAN ROSTAND 91025 EVRY CEDEX", "14475");
insert into iut (nomIut, adresse, nbEtudiants) values ("Chambéry", "DOMAINE SCIENTIFIQUE DU BOURGET-DU-LAC 73376 LE BOURGET DU LAC CEDEX", "17490");
insert into iut (nomIut, adresse, nbEtudiants) values ("Nice", "41 BOULEVARD NAPOLEON III 06041 NICE CEDEX", "24166");
insert into iut (nomIut, adresse, nbEtudiants) values ("Amiens", "AVENUE DES FACULTES 80025 AMIENS CEDEX 1", "16196");
insert into iut (nomIut, adresse, nbEtudiants) values ("Thionville-Yutz", "IMPASSE ALFRED KASTLER 57970 YUTZ", "30757");
insert into iut (nomIut, adresse, nbEtudiants) values ("Saint-Dié-des-Vosges", "11 RUE DE L'UNIVERSITE 88100 ST DIE", "33716");
insert into iut (nomIut, adresse, nbEtudiants) values ("Caen", "2 BOULEVARD DU MARECHAL JUIN 14032 CAEN CEDEX", "24984");
insert into iut (nomIut, adresse, nbEtudiants) values ("Reims", "RUE DES CRAYERES 51687 REIMS CEDEX 2", "38377");
insert into iut (nomIut, adresse, nbEtudiants) values ("Villetaneuse", "AVENUE JEAN BAPTISTE CLEMENT 93430 VILLETANEUSE", "16418");
insert into iut (nomIut, adresse, nbEtudiants) values ("Nantes", "3 RUE DU MARECHAL JOFFRE 44041 NANTES CEDEX 1", "25049");
insert into iut (nomIut, adresse, nbEtudiants) values ("Angers", "4 BOULEVARD LAVOISIER 49016 ANGERS CEDEX 01", "32576");
insert into iut (nomIut, adresse, nbEtudiants) values ("Bobigny", "1 RUE DE CHABLIS 93000 BOBIGNY", "13898");
insert into iut (nomIut, adresse, nbEtudiants) values ("Saint-Etienne", "28 AVENUE LEON JOUHAUX 42023 ST ETIENNE CEDEX 2", "14766");
