insert into iut (nomIut, adresse, nbEtudiants) values ("Colmar", "34 RUE GRILLENBREIT 68008 COLMAR CEDEX", "16095");
insert into iut (nomIut, adresse, nbEtudiants) values ("Mulhouse", "61 RUE ALBERT CAMUS 68093 MULHOUSE CEDEX", "23599");
insert into iut (nomIut, adresse, nbEtudiants) values ("Haguenau", "30 RUE DU MAIRE ANDRE TRABAND 67500 HAGUENAU", "13802");
insert into iut (nomIut, adresse, nbEtudiants) values ("Illkirch", "72 ROUTE DU RHIN 67400 ILLKIRCH GRAFFENSTADEN", "36847");
insert into iut (nomIut, adresse, nbEtudiants) values ("Schiltigheim", "1 ALLEE D'ATHENES 67300 SCHILTIGHEIM", "35124");
insert into iut (nomIut, adresse, nbEtudiants) values ("Bordeaux-I", "15 RUE NAUDET 33175 GRADIGNAN CEDEX", "26759");
insert into iut (nomIut, adresse, nbEtudiants) values ("Bordeaux-IV", "35 AVENUE ABADIE 33072 BORDEAUX CEDEX", "11604");
insert into iut (nomIut, adresse, nbEtudiants) values ("Périgueux", "39 RUE PAUL MAZY 24019 PERIGUEUX CEDEX", "38273");
insert into iut (nomIut, adresse, nbEtudiants) values ("Bayonne", "2 ALLEE DU PARC MONTAURY 64600 ANGLET", "20599");
insert into iut (nomIut, adresse, nbEtudiants) values ("Pays de l'Adour", "AVENUE DE L UNIVERSITE 64000 PAU", "26460");
insert into iut (nomIut, adresse, nbEtudiants) values ("Clermont-Ferrand", "ENSEMBLE UNIVERSITAIRE DES CEZEAUX 63172 AUBIERE CEDEX", "22126");
insert into iut (nomIut, adresse, nbEtudiants) values ("Montluçon", "AVENUE ARISTIDE BRIAND 03107 MONTLUCON CEDEX", "32765");
insert into iut (nomIut, adresse, nbEtudiants) values ("Alençon", "SITE UNIVERSITAIRE DE MONTFOULON 61250 DAMIGNY", "33457");
insert into iut (nomIut, adresse, nbEtudiants) values ("Caen", "2 BOULEVARD DU MARECHAL JUIN 14032 CAEN CEDEX", "34330");
insert into iut (nomIut, adresse, nbEtudiants) values ("Cherbourg", "RUE MAX POL FOUCHET 50130 CHERBOURG OCTEVILLE", "15580");
insert into iut (nomIut, adresse, nbEtudiants) values ("Chalon-sur-Saône", "1 ALLEE DES GRANGES FORESTIERS 71100 CHALON SUR SAONE", "17482");
insert into iut (nomIut, adresse, nbEtudiants) values ("Dijon", "BOULEVARD DOCTEUR PETIJEAN 21078 DIJON CEDEX", "26420");
insert into iut (nomIut, adresse, nbEtudiants) values ("Creusot", "12 RUE DE LA FONDERIE 71200 LE CREUSOT", "37252");
insert into iut (nomIut, adresse, nbEtudiants) values ("Brest", "RUE DE KERGOAT 29287 BREST CEDEX", "11870");
insert into iut (nomIut, adresse, nbEtudiants) values ("Quimper", "2 RUE DE L'UNIVERSITE 29334 QUIMPER CEDEX", "13189");
insert into iut (nomIut, adresse, nbEtudiants) values ("Lorient", "10 RUE JEAN ZAY 56325 LORIENT CEDEX", "34402");
insert into iut (nomIut, adresse, nbEtudiants) values ("Vannes", "8 RUE MONTAIGNE 56017 VANNES CEDEX", "33188");
insert into iut (nomIut, adresse, nbEtudiants) values ("Lannion", "RUE EDOUARD BRANLY 22302 LANNION CEDEX", "12608");
insert into iut (nomIut, adresse, nbEtudiants) values ("Rennes", "3 RUE DU CLOS COURTEL 35014 RENNES CEDEX 7", "26701");
insert into iut (nomIut, adresse, nbEtudiants) values ("Saint-Brieuc", "18 RUE HENRI WALLON 22015 ST BRIEUC CEDEX", "25100");
insert into iut (nomIut, adresse, nbEtudiants) values ("Saint-Malo", "RUE DE LA CROIX DESILLES 35409 ST MALO CEDEX", "32525");
insert into iut (nomIut, adresse, nbEtudiants) values ("Bourges", "63 AVENUE DE LATTRE DE TASSIGNY 18020 BOURGES CEDEX", "14446");
insert into iut (nomIut, adresse, nbEtudiants) values ("Chartres", "1 PLACE PIERRE MENDES FRANCE 28000 CHARTRES", "33852");
insert into iut (nomIut, adresse, nbEtudiants) values ("l'Indre", "2 AVENUE FRANCOIS MITTERRAND 36000 CHATEAUROUX", "31242");
insert into iut (nomIut, adresse, nbEtudiants) values ("Orléans", "RUE D ISSOUDUN 45067 ORLEANS CEDEX 2", "35275");
insert into iut (nomIut, adresse, nbEtudiants) values ("Blois", "3 PLACE JEAN JAURES CS 2903 41029 BLOIS CEDEX", "21371");
insert into iut (nomIut, adresse, nbEtudiants) values ("Tours", "29 RUE DU PONT VOLANT 37082 TOURS CEDEX 2", "11807");
insert into iut (nomIut, adresse, nbEtudiants) values ("Reims", "RUE DES CRAYERES 51687 REIMS CEDEX 2", "29336");
insert into iut (nomIut, adresse, nbEtudiants) values ("Troyes", "9 RUE DE QUEBEC 10026 TROYES CEDEX", "22178");
insert into iut (nomIut, adresse, nbEtudiants) values ("Corte", "QUARTIER GRIMALDI 20250 CORTE", "13874");
insert into iut (nomIut, adresse, nbEtudiants) values ("Belfort-Montbéliard", "RUE ENGEL GROS 90016 BELFORT CEDEX", "32525");
insert into iut (nomIut, adresse, nbEtudiants) values ("Besançon", "30 AVENUE DE L' OBSERVATOIRE 25009 BESANCON CEDEX", "38502");
insert into iut (nomIut, adresse, nbEtudiants) values ("Havre", "PLACE ROBERT SCHUMANN 76610 LE HAVRE", "15065");
insert into iut (nomIut, adresse, nbEtudiants) values ("Evreux", "55 RUE SAINT GERMAIN 27000 EVREUX", "13703");
insert into iut (nomIut, adresse, nbEtudiants) values ("Rouen", "RUE LAVOISIER 76821 MONT ST AIGNAN CEDEX", "20047");
insert into iut (nomIut, adresse, nbEtudiants) values ("Cergy-Pontoise", "RUE D'ERAGNY 95031 CERGY PONTOISE CEDEX", "35489");
insert into iut (nomIut, adresse, nbEtudiants) values ("Evry", "22 ALLEE JEAN ROSTAND 91025 EVRY CEDEX", "25939");
insert into iut (nomIut, adresse, nbEtudiants) values ("Marne-la-Vallée", "4 RUE ALBERT EINSTEIN 77420 CHAMPS SUR MARNE", "20045");
insert into iut (nomIut, adresse, nbEtudiants) values ("l'avenue de Versailles", "143 AVENUE DE VERSAILLES 75016 PARIS", "35442");
insert into iut (nomIut, adresse, nbEtudiants) values ("Paris-VII", "2 PLACE JUSSIEU 75251 PARIS CEDEX 05", "38556");
insert into iut (nomIut, adresse, nbEtudiants) values ("Montreuil", "140 RUE DE LA NOUVELLE FRANCE 93100 MONTREUIL", "28276");
insert into iut (nomIut, adresse, nbEtudiants) values ("Tremblay-en-France", "RUE DE LA RAPERIE 93290 TREMBLAY EN FRANCE", "34864");
insert into iut (nomIut, adresse, nbEtudiants) values ("Ville-d'Avray", "50 RUE DE SÈVRES 92410 VILLE D AVRAY", "25757");
insert into iut (nomIut, adresse, nbEtudiants) values ("Cachan", "9 AVENUE DIVISION LECLERC 94230 CACHAN", "19990");
insert into iut (nomIut, adresse, nbEtudiants) values ("Orsay", "PLATEAU DE MOULON 91400 ORSAY", "25809");
insert into iut (nomIut, adresse, nbEtudiants) values ("Sceaux", "8 AVENUE CAUCHY 92330 SCEAUX", "16418");
insert into iut (nomIut, adresse, nbEtudiants) values ("Créteil", "61 AVENUE DU GENERAL DE GAULLE 94010 CRETEIL CEDEX", "32992");
insert into iut (nomIut, adresse, nbEtudiants) values ("Seine-et-Marne Sud", "AVENUE PIERRE POINT 77127 LIEUSAINT", "36583");
insert into iut (nomIut, adresse, nbEtudiants) values ("Bobigny", "1 RUE DE CHABLIS 93000 BOBIGNY", "22398");
insert into iut (nomIut, adresse, nbEtudiants) values ("Saint-Denis", "PLACE DU 8 MAI 1945 93206 ST DENIS CEDEX", "30502");
insert into iut (nomIut, adresse, nbEtudiants) values ("Villetaneuse", "AVENUE JEAN BAPTISTE CLEMENT 93430 VILLETANEUSE", "25880");
insert into iut (nomIut, adresse, nbEtudiants) values ("Mantes-la-Jolie", "7 RUE JEAN HOET 78200 MANTES LA JOLIE", "21697");
insert into iut (nomIut, adresse, nbEtudiants) values ("Vélizy", "10 AVENUE DE L'EUROPE 78129 VELIZY VILLACOUBLAY", "13685");
insert into iut (nomIut, adresse, nbEtudiants) values ("Béziers", "Béziers BP 50438 34505 BEZIERS cedex", "38220");
insert into iut (nomIut, adresse, nbEtudiants) values ("Montpellier", "99 AVENUE D' OCCITANIE 34296 MONTPELLIER CEDEX 5", "19237");
insert into iut (nomIut, adresse, nbEtudiants) values ("Perpignan", "CHEMIN DE LA PASSIO VELLA 66962 PERPIGNAN CEDEX", "33052");
insert into iut (nomIut, adresse, nbEtudiants) values ("Limousin", "ALLEE ANDRE MAUROIS 87065 LIMOGES CEDEX", "16149");
insert into iut (nomIut, adresse, nbEtudiants) values ("Metz", "ILE DU SAULCY 57045 METZ CEDEX 1", "19106");
insert into iut (nomIut, adresse, nbEtudiants) values ("Moselle-Est", "7 RUE ALEXANDRE DE GEIGER 57200 SARREGUEMINES", "24135");
insert into iut (nomIut, adresse, nbEtudiants) values ("Thionville-Yutz", "IMPASSE ALFRED KASTLER 57970 YUTZ", "22225");
insert into iut (nomIut, adresse, nbEtudiants) values ("Henri Poincaré de Longwy ", "186 RUE DE LORRAINE 54400 COSNES ET ROMAIN", "38895");
insert into iut (nomIut, adresse, nbEtudiants) values ("Saint-Dié-des-Vosges", "11 RUE DE L'UNIVERSITE 88100 ST DIE", "25391");
insert into iut (nomIut, adresse, nbEtudiants) values ("Epinal-Hubert Curien", "7 RUE DES FUSILLES RESIST 88010 EPINAL CEDEX", "38886");
insert into iut (nomIut, adresse, nbEtudiants) values ("Nancy-Charlemagne", "2 TER BOULEVARD CHARLEMAGNE 54052 NANCY CEDEX", "17344");
insert into iut (nomIut, adresse, nbEtudiants) values ("Rodez", "33 AVENUE DU 8 MAI 1945 12006 RODEZ CEDEX", "13504");
insert into iut (nomIut, adresse, nbEtudiants) values ("Blagnac", "1 PLACE GEORGES BRASSENS 31703 BLAGNAC CEDEX", "11308");
insert into iut (nomIut, adresse, nbEtudiants) values ("Figeac", "AVENUE DE NAYRAC 46100 FIGEAC", "18422");
insert into iut (nomIut, adresse, nbEtudiants) values ("Tarbes", "1 RUE LAUTREAMONT 65016 TARBES CEDEX", "33085");
insert into iut (nomIut, adresse, nbEtudiants) values ("Toulouse", "115 ROUTE DE NARBONNE 31077 TOULOUSE CEDEX", "33543");
insert into iut (nomIut, adresse, nbEtudiants) values ("Béthune", "1230 RUE DE L'UNIVERSITE 62408 BETHUNE CEDEX", "21167");
insert into iut (nomIut, adresse, nbEtudiants) values ("Lens", "7 RUE DE L'UNIVERSITE 62307 LENS CEDEX", "34120");
insert into iut (nomIut, adresse, nbEtudiants) values ("Lille-I", "CITE SCIENTIFIQUE 59653 VILLENEUVE D'ASCQ CEDEX", "36475");
insert into iut (nomIut, adresse, nbEtudiants) values ("Lille-II", "ROND-POINT DE L'EUROPE 59060 ROUBAIX CEDEX 01", "37004");
insert into iut (nomIut, adresse, nbEtudiants) values ("Lille-III", "35 RUE SAINTE BARBE 59208 TOURCOING CEDEX", "36817");
insert into iut (nomIut, adresse, nbEtudiants) values ("Calais - Boulogne", "RUE LOUIS DAVID 62228 CALAIS CEDEX", "25339");
insert into iut (nomIut, adresse, nbEtudiants) values ("Saint-Omer - Dunkerque", "AVENUE DESCARTES 62968 LONGUENESSE CEDEX", "10546");
insert into iut (nomIut, adresse, nbEtudiants) values ("Valenciennes", "Le Mont Houy 59313 VALENCIENNES CEDEX", "22836");
insert into iut (nomIut, adresse, nbEtudiants) values ("Kourou", "LOTISS. BRANLY 4 AV CHAUDAT 97387 KOUROU CEDEX", "32913");
insert into iut (nomIut, adresse, nbEtudiants) values ("La Réunion", "40 AVENUE DE SOWETO 97455 ST PIERRE CEDEX", "13824");
insert into iut (nomIut, adresse, nbEtudiants) values ("Aix-en-Provence", "AVENUE GASTON BERGER 13625 AIX EN PROVENCE CEDEX", "25855");
insert into iut (nomIut, adresse, nbEtudiants) values ("Marseille", "142 TRAVERSE CHARLES SUSINI 13388 MARSEILLE CEDEX 13", "29990");
insert into iut (nomIut, adresse, nbEtudiants) values ("Avignon", "337 CHEMIN DE MAINAJARIES 84911 AVIGNON CEDEX 9", "21822");
insert into iut (nomIut, adresse, nbEtudiants) values ("Nice", "41 BOULEVARD NAPOLEON III 06041 NICE CEDEX", "29578");
insert into iut (nomIut, adresse, nbEtudiants) values ("Toulon", "AVENUE DE L'UNIVERSITE 83957 LA GARDE CEDEX", "35722");
insert into iut (nomIut, adresse, nbEtudiants) values ("Angers", "4 BOULEVARD LAVOISIER 49016 ANGERS CEDEX 01", "30419");
insert into iut (nomIut, adresse, nbEtudiants) values ("Mans", "AVENUE OLIVIER MESSIAEN 72085 LE MANS CEDEX 9", "13491");
insert into iut (nomIut, adresse, nbEtudiants) values ("Laval", "52 RUE DES DRS CALMETTE ET GUERI 53020 LAVAL CEDEX 9", "27738");
insert into iut (nomIut, adresse, nbEtudiants) values ("la Roche-sur-Yon", "18 BOULEVARD GASTON DEFFERRE 85035 LA ROCHE SUR YON CEDEX", "23973");
insert into iut (nomIut, adresse, nbEtudiants) values ("Nantes", "3 RUE DU MARECHAL JOFFRE 44041 NANTES CEDEX 1", "17295");
insert into iut (nomIut, adresse, nbEtudiants) values ("Saint-Nazaire", "58 RUE MICHEL ANGE 44600 ST NAZAIRE", "35957");
insert into iut (nomIut, adresse, nbEtudiants) values ("l'Aisne", "2 RUE PIERRE CURIE 02000 LAON", "15546");
insert into iut (nomIut, adresse, nbEtudiants) values ("Amiens", "AVENUE DES FACULTES 80025 AMIENS CEDEX 1", "31038");
insert into iut (nomIut, adresse, nbEtudiants) values ("Beauvais", "54 BOULEVARD SAINT ANDRE 60000 BEAUVAIS", "15326");
insert into iut (nomIut, adresse, nbEtudiants) values ("La Rochelle", "15 RUE F DE VAUX DE FOLETIER 17026 LA ROCHELLE CEDEX 1", "37417");
insert into iut (nomIut, adresse, nbEtudiants) values ("Angoulême", "4 AVENUE DE VARSOVIE 16021 ANGOULEME CEDEX", "32622");
insert into iut (nomIut, adresse, nbEtudiants) values ("Poitiers", "6 ALLEE JEAN MONNET 86010 POITIERS CEDEX", "31657");
insert into iut (nomIut, adresse, nbEtudiants) values ("Annecy", "9 RUE DE L'ARC EN CIEL 74942 ANNECY LE VIEUX CEDEX", "35408");
insert into iut (nomIut, adresse, nbEtudiants) values ("Chambéry", "DOMAINE SCIENTIFIQUE DU BOURGET-DU-LAC 73376 LE BOURGET DU LAC CEDEX", "31892");
insert into iut (nomIut, adresse, nbEtudiants) values ("Grenoble-I", "151 RUE DE LA PAPETERIE 38402 ST MARTIN D HERES CEDEX", "11466");
insert into iut (nomIut, adresse, nbEtudiants) values ("Grenoble-II", "2 PLACE DOYEN GOSSE 38031 GRENOBLE CEDEX", "27285");
insert into iut (nomIut, adresse, nbEtudiants) values ("Lyon-I", "1 RUE DE LA TECHNOLOGIE 69622 VILLEURBANNE CEDEX", "30705");
insert into iut (nomIut, adresse, nbEtudiants) values ("Bron", "160 BOULEVARD DE L'UNIVERSITE 69676 BRON CEDEX", "21177");
insert into iut (nomIut, adresse, nbEtudiants) values ("Lyon-III", "6 COURS ALBERT THOMAS 69355 LYON CEDEX 08", "33892");
insert into iut (nomIut, adresse, nbEtudiants) values ("Roanne", "20 AVENUE DE PARIS 42334 ROANNE CEDEX", "33853");
insert into iut (nomIut, adresse, nbEtudiants) values ("Saint-Etienne", "28 AVENUE LEON JOUHAUX 42023 ST ETIENNE CEDEX 2", "15029");
